FROM hexpm/elixir:1.18.4-erlang-27.3.4.2-debian-bookworm-20260316-slim
RUN apt-get update && apt-get install -y --no-install-recommends git build-essential ca-certificates curl inotify-tools && rm -rf /var/lib/apt/lists/*
WORKDIR /app
